name: ontrac_coverage
version: 1.0.0
profile: ontrac

model-paths: ["models"]
snapshot-paths: ["snapshots"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
test-paths: ["tests"]

clean-targets:
  - "target"
  - "dbt_packages"

on-run-start:
  - "COPY INTO ontrac.raw.zip_surcharge FROM (SELECT $1::STRING, $2::STRING, $3::DATE, $4::INTEGER, $5::STRING, $6::STRING, REGEXP_SUBSTR(METADATA$FILENAME, 'dt=([0-9]{4}-[0-9]{2}-[0-9]{2})', 1, 1, 'e', 1)::DATE, METADATA$FILENAME FROM @ontrac.raw.ontrac_structured) PATTERN = '.*source=zip-surcharge/.*rows[.]csv' ON_ERROR = ABORT_STATEMENT"
  - "COPY INTO ontrac.raw.map_coverage FROM (SELECT $1::STRING, $2::STRING, $3::INTEGER, $4::STRING, $5::STRING, $6::INTEGER, $7::INTEGER, $8::STRING, $9::STRING, $10::STRING, $11::DATE, $12::STRING, METADATA$FILENAME FROM @ontrac.raw.ontrac_structured) PATTERN = '.*source=coverage-maps/.*rows[.]csv' ON_ERROR = ABORT_STATEMENT"
  - "COPY INTO ontrac.raw.service_alerts FROM (SELECT $1::DATE, $2::INTEGER, $3::STRING, $4::STRING, $5::STRING, $6::STRING, REGEXP_SUBSTR(METADATA$FILENAME, 'dt=([0-9]{4}-[0-9]{2}-[0-9]{2})', 1, 1, 'e', 1)::DATE, METADATA$FILENAME FROM @ontrac.raw.ontrac_structured) PATTERN = '.*source=service-alerts/.*rows[.]csv' ON_ERROR = ABORT_STATEMENT"
  - "COPY INTO ontrac.raw.service_alerts_parsed FROM (SELECT $1::DATE, $2::STRING, $3::STRING, $4::DATE, $5::STRING, $6::STRING, $7::STRING, $8::STRING, $9::STRING, $10::STRING, $11::STRING, REGEXP_SUBSTR(METADATA$FILENAME, 'dt=([0-9]{4}-[0-9]{2}-[0-9]{2})', 1, 1, 'e', 1)::DATE, METADATA$FILENAME FROM @ontrac.raw.ontrac_structured) PATTERN = '.*source=service-alerts-parsed/.*rows[.]csv' ON_ERROR = ABORT_STATEMENT"

models:
  ontrac_coverage:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts

snapshots:
  ontrac_coverage:
    +target_schema: snapshots