USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS ontrac_wh
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS ontrac;

CREATE SCHEMA IF NOT EXISTS ontrac.raw;
CREATE SCHEMA IF NOT EXISTS ontrac.staging;
CREATE SCHEMA IF NOT EXISTS ontrac.marts;
CREATE SCHEMA IF NOT EXISTS ontrac.snapshots;

USE WAREHOUSE ontrac_wh;
USE DATABASE ontrac;
USE SCHEMA raw;

SELECT CURRENT_ACCOUNT(), CURRENT_REGION(), CURRENT_WAREHOUSE(), CURRENT_DATABASE(), CURRENT_SCHEMA();